### ISSUE TITLE
Simultaneous move from the second player before the first user selects a piece to substitute a pawn.

### ISSUE THREAD

**Issue by Khislatjon** [nicklockwood/Chess#2]
The second player should wait before the first user selects a piece for the pawn. Otherwise, the app will not work correctly in stalemate cases. For example: 
<img width="393" alt="Screenshot 2024-04-17 at 23 51 45" src="https://github.com/nicklockwood/Chess/assets/58033343/cde798e6-f76b-4908-ac5b-453842ae6162">

Here whites should move. If I promote the pawn to a rook, there should be a stalemate. However, the king moves G8 (only move), before I select a rook:
<img width="395" alt="Screenshot 2024-04-17 at 23 52 16" src="https://github.com/nicklockwood/Chess/assets/58033343/d89970a4-fd42-4328-94e6-e0b29b26b1c4">

**Comment by nicklockwood** [comment]
Thanks for flagging and fixing!
